<a href="https://colab.research.google.com/github/ZahibVentura/Simulaci-n-1/blob/main/M%C3%A9todo_transporte.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.zeros((3,2))
print(a)
a[1][1]=2
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 2.]
 [0. 0.]]


In [10]:
import numpy as np

filas = int(input('Ingrese  el número de filas: '))
columnas = int(input('Ingrese  el número de columnas: '))
aux = np.zeros((filas,columnas))
tabla_iteraciones = np.zeros((filas,columnas))
print('TABLA DE PRECIOS')
for i in range(filas):
  for j in range(columnas):
    print('Ingrese la entrada [',i+1,']','[',j+1,']')
    valor=float(input(': '))
    aux[i][j]=valor

demanda = []
oferta = []

print('ingrese la demanda')
for i in range(columnas):
  print('demanda ','[',i+1,']')
  dem = int(input(':'))
  demanda.append(dem)

print('ingrese la oferta')
for i in range(filas):
  print('oferta ','[',i+1,']')
  ofe = int(input(':'))
  oferta.append(ofe)

for i in range(filas):
  for j in range(columnas):
    if demanda[j] <= oferta[i]:
      asig = demanda[j]
    else:
      asig = oferta[i]

    tabla_iteraciones[i][j] = asig
    demanda[j]=demanda[j]-asig
    oferta[i]=oferta[i]-asig

print(tabla_iteraciones)
print('\n')
print(aux)

costo=-1
while costo<0:
  C=100000
  for i in range(1):
    for j in range(columnas):
      if tabla_iteraciones[i][j]!=0 and tabla_iteraciones[i+1][j]!=0:
        a,b=i,j
        for y in range(filas):
          for z in range(columnas):
            if tabla_iteraciones[y][z]==0:
              if y>a and z<b:
                costo = aux[y][z]-aux[y-1][z]+aux[a][b]-aux[a+1][b]
                if costo<=C:
                  C=costo
                  A,B=y,z

                  if tabla_iteraciones[A-1][B]<=tabla_iteraciones[a+1][b]:
                    menor = tabla_iteraciones[A-1][B]
                  elif tabla_iteraciones[A-1][B]>tabla_iteraciones[a+1][b]:
                    menor = tabla_iteraciones[a+1][b]
              elif y<=a and z<b:
                costo = aux[y][z]-aux[y+1][z]-aux[a][b]+aux[a+1][b]
                if costo<=C:
                  C=costo
                  A,B=y,z
                  if tabla_iteraciones[A+1][B]<=tabla_iteraciones[a][b]:
                    menor = tabla_iteraciones[A+1][B]
                  elif tabla_iteraciones[A+1][B]>tabla_iteraciones[a][b]:
                    menor = tabla_iteraciones[a][b]
              elif y<=a and z>b:
                costo = aux[y][z]-aux[y+1][z]-aux[a][b]+aux[a+1][b]
                if costo<=C:
                  C=costo
                  A,B=y,z
                  if tabla_iteraciones[A+1][B]<=tabla_iteraciones[a][b]:
                    menor = tabla_iteraciones[A+1][B]
                  elif tabla_iteraciones[A+1][B]>tabla_iteraciones[a][b]:
                    menor = tabla_iteraciones[a][b]
              elif y>a and z>b:
                costo = aux[y][z]-aux[y-1][z]+aux[a][b]-aux[a+1][b]
                if costo<=C:
                  C=costo
                  A,B=y,z
                  if tabla_iteraciones[A-1][B]<=tabla_iteraciones[a+1][b]:
                    menor = tabla_iteraciones[A-1][B]
                  elif tabla_iteraciones[A-1][B]>tabla_iteraciones[a+1][b]:
                    menor = tabla_iteraciones[a+1][b]

  for i in range(filas):
    for j in range(columnas):
      if i==A and j==B:
        if A==0:
          tabla_iteraciones[i][j]=tabla_iteraciones[i][j]+menor
          tabla_iteraciones[a][b]=tabla_iteraciones[a][b]-menor
          tabla_iteraciones[a+1][b]=tabla_iteraciones[a+1][b]+menor
          tabla_iteraciones[A+1][B]=tabla_iteraciones[A+1][B]-menor
        elif A==1:
          tabla_iteraciones[i][j]=tabla_iteraciones[i][j]+menor
          tabla_iteraciones[a][b]=tabla_iteraciones[a][b]+menor
          tabla_iteraciones[a+1][b]=tabla_iteraciones[a+1][b]-menor
          tabla_iteraciones[A-1][B]=tabla_iteraciones[A-1][B]-menor

  print('el costo es:',costo)
  print('Entrada [i][j]:',A,',',B)
  print(menor)
  print(tabla_iteraciones)










Ingrese  el número de filas: 2
Ingrese  el número de columnas: 7
TABLA DE PRECIOS
Ingrese la entrada [ 1 ] [ 1 ]
: 0.84
Ingrese la entrada [ 1 ] [ 2 ]
: 0.63
Ingrese la entrada [ 1 ] [ 3 ]
: 1.17
Ingrese la entrada [ 1 ] [ 4 ]
: 3.02
Ingrese la entrada [ 1 ] [ 5 ]
: 3.40
Ingrese la entrada [ 1 ] [ 6 ]
: 3.60
Ingrese la entrada [ 1 ] [ 7 ]
: 0
Ingrese la entrada [ 2 ] [ 1 ]
: 1.23
Ingrese la entrada [ 2 ] [ 2 ]
: 0.37
Ingrese la entrada [ 2 ] [ 3 ]
: 1.29
Ingrese la entrada [ 2 ] [ 4 ]
: 2.04
Ingrese la entrada [ 2 ] [ 5 ]
: 2.81
Ingrese la entrada [ 2 ] [ 6 ]
: 2.85
Ingrese la entrada [ 2 ] [ 7 ]
: 0
ingrese la demanda
demanda  [ 1 ]
:400
demanda  [ 2 ]
:500
demanda  [ 3 ]
:200
demanda  [ 4 ]
:200
demanda  [ 5 ]
:400
demanda  [ 6 ]
:300
demanda  [ 7 ]
:500
ingrese la oferta
oferta  [ 1 ]
:1500
oferta  [ 2 ]
:1000
[[400. 500. 200. 200. 200.   0.   0.]
 [  0.   0.   0.   0. 200. 300. 500.]]


[[0.84 0.63 1.17 3.02 3.4  3.6  0.  ]
 [1.23 0.37 1.29 2.04 2.81 2.85 0.  ]]
el costo es: -0.390

In [ ]:
def redistribuir(matriz, oferta, demanda):
  filas, columnas = matriz.shape
  while True:
    movido = False
    for i in range(filas):
      for j in range(columnas):
        if matriz[i][j] != 0:
          # Intentar mover hacia la derecha
          if j + 1 < columnas and matriz[i][j + 1] == 0:
            cantidad = min(matriz[i][j], demanda[j])
            matriz[i][j] -= cantidad
            matriz[i][j + 1] += cantidad
            demanda[j] -= cantidad
            movido = True
          # Intentar mover hacia abajo
          elif i + 1 < filas and matriz[i + 1][j] == 0:
            cantidad = min(matriz[i][j], oferta[i])
            matriz[i][j] -= cantidad
            matriz[i + 1][j] += cantidad
            oferta[i] -= cantidad
            movido = True
    if not movido:
      break
  return matriz

# Ejemplo de uso
matriz = np.array([[10, 0, 20], [0, 30, 40]])
oferta = [30, 70]
demanda = [40, 30, 30]
resultado = redistribuir(matriz.copy(), oferta.copy(), demanda.copy())
print("Matriz original:")
print(matriz)
print("Matriz redistribuida:")
print(resultado)

Matriz original:
[[10  0 20]
 [ 0 30 40]]
Matriz redistribuida:
[[ 0 10 20]
 [ 0 30 40]]
